name: Build PDF

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Cache APT packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: texlive-latex-base texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-bibtex-extra biber
          version: 1.0

      - name: Cache texlive directory
        uses: actions/cache@v3
        with:
          path: |
            /usr/local/share/texlive
            /usr/local/texlive
            ~/.texlive
          key: texlive-${{ runner.os }}-${{ hashFiles('**/*.tex') }}
          restore-keys: |
            texlive-${{ runner.os }}-

      - name: Build PDFs
        run: |
          cd docs/VnVPlan
          pdflatex -interaction=nonstopmode VnVPlan.tex
          bibtex VnVPlan
          pdflatex -interaction=nonstopmode VnVPlan.tex
          pdflatex -interaction=nonstopmode VnVPlan.tex

      - name: Commit and push PDFs
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add docs/VnVPlan/VnVPlan.pdf
          git commit -m "Auto-build VnVPlan PDF" || echo "No changes to commit"
          git push
