name: Build PDF

on:
  push:
    paths:
      - 'docs/VnVPlan/**/*.tex'
      - 'docs/projMngmnt/**/*.tex'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Compile LaTeX document - VnVPlan
        if: contains(github.event.head_commit.modified, 'docs/VnVPlan/')
        uses: xu-cheng/latex-action@v3
        with:
          root_file: VnVPlan.tex
          working_directory: docs/VnVPlan
          args: -pdf -file-line-error -interaction=nonstopmode
          post_compile: |
            bibtex VnVPlan
            pdflatex -interaction=nonstopmode VnVPlan.tex
            pdflatex -interaction=nonstopmode VnVPlan.tex

      - name: Compile LaTeX document - POC Team Contribution
        if: contains(github.event.head_commit.modified, 'docs/projMngmnt/')
        uses: xu-cheng/latex-action@v3
        with:
          root_file: POC_Team_Contrib.tex
          working_directory: docs/projMngmnt
          args: -pdf -file-line-error -interaction=nonstopmode
          post_compile: |
            pdflatex -interaction=nonstopmode POC_Team_Contrib.tex

      - name: Commit and push PDFs
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add docs/VnVPlan/VnVPlan.pdf
          git add docs/projMngmnt/POC_Team_Contrib.pdf
          git commit -m "Auto-build PDFs" || echo "No changes to commit"
          git push
