name: Build PDF

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Cache APT packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: texlive-full latexmk biber texlive-bibtex-extra default-jre plantuml
          version: 1.0

      - name: Cache texlive directory
        uses: actions/cache@v3
        with:
          path: |
            /usr/local/share/texlive
            /usr/local/texlive
            ~/.texlive
          key: texlive-${{ runner.os }}-${{ hashFiles('**/*.tex') }}
          restore-keys: |
            texlive-${{ runner.os }}-

      - name: Install Asciidoctor PDF
        uses: reitzig/actions-asciidoctor@v2.0.1
        with:
          version: 2.0.20

      - name: Build PDFs
        run: |
          # Find all Makefiles in docs subdirectories and execute them
          find docs -mindepth 2 -name "Makefile" -execdir make \;

      - name: Commit and push PDFs
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add docs/**/*.pdf
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-generated PDFs" && git push)
