name: Build PDF

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: docs/VnVPlan/VnVPlan.tex
          working_directory: docs/VnVPlan
          args: -pdf -file-line-error -interaction=nonstopmode
          post_compile: |
            bibtex VnVPlan
            pdflatex -interaction=nonstopmode VnVPlan.tex
            pdflatex -interaction=nonstopmode VnVPlan.tex

      - name: Commit and push PDFs
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add docs/VnVPlan/VnVPlan.pdf
          git commit -m "Auto-build VnVPlan PDF" || echo "No changes to commit"
          git push
