name: Lint and Format

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: "./src/package-lock.json"

      - name: Install Dependencies
        run: npm ci --legacy-peer-deps

      - name: Run Lint
        run: npm run lint

  prettier:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: "./src/package-lock.json"

      - name: Install Dependencies
        run: npm ci --legacy-peer-deps

      - name: Run Prettier
        run: npm run format
