name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: "./src/package-lock.json"

      - name: Install Dependencies
        run: npm ci --legacy-peer-deps

      - name: Run Jest Tests
        run: npm test

      - name: Upload Test Coverage
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: coverage-report
          path: ./src/coverage
          retention-days: 30